apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "helm.fullname" . }}-configmap
    labels:
        {{- include "helm.labels" . | nindent 8 }}
data:
    DB_URL: {{ .Values.dbUrl }}
    ERP_URL: {{ .Values.erpUrl }}
    BCB_URL: {{ .Values.bcbUrl }}