apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "helm.fullname" . }}-configmap
    labels:
        {{- include "helm.labels" . | nindent 8 }}
data:
    DB_URI: {{ .Values.dbUrl }}
    DB_USER: {{ .Values.dbUser }}
    ITAU_URL: {{ .Values.erpUrl }}
    BCB_URL: {{ .Values.bcbUrl }}
    DB_DIALECT: {{ .Values.dbDialect }}