apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "helm.fullname" . }}-configmap
    labels:
        {{- include "helm.labels" . | nindent 8 }}
data:
    DB_URI: {{ .Values.DB_URI }}
    DB_USER: {{ .Values.DB_USER }}
    ITAU_URL: {{ .Values.ITAU_URL }}
    BCB_URL: {{ .Values.BCB_URL }}
    DB_DIALECT: {{ .Values.DB_DIALECT }}