apiVersion: v1
kind: Secret
metadata:
    name: {{ include "helm.fullname" . }}-secret
    labels:
        {{- include "helm.labels" . | nindent 8 }}
type: {{ .Values.secretType }}
data:
    DB_PASS: {{ .Values.dbPass }}