apiVersion: v1
kind: Secret
metadata:
    name: {{ include "helm.fullname" . }}-secret
    labels:
        {{- include "helm.labels" . | nindent 8 }}
type: {{ .Values.secretType }}
stringData:
    DB_PASSWORD: {{ .Values.DB_PASSWORD | quote }}